import d4rl
import gym
env = gym.make("maze2d-umaze-v1")
dataset = env.get_dataset()
dataset = d4rl.qlearning_dataset(env)
print(dataset.keys())
# print(dataset[0])
print(dataset['observations'].shape)
print(dataset['actions'].shape)
print(dataset['next_observations'].shape)
print(dataset['rewards'].shape)
print(dataset['terminals'].shape)
# print(dataset['observations'][:1])
# print(dataset.keys())
# print(dataset['terminals'])